name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #timeout-minutes: 20000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Start server
        run:  node server.js &
      - name: Wait for server to start
        run: sleep 10 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 20000
        with:
          browser: chrome
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: nodebattleship-pipeline-results
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          #SLACK_ICON: 
          SLACK_MESSAGE: 'ci.yml Results'
          SLACK_TITLE: Play through regression Test
          SLACK_USERNAME: none
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

