name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #timeout-minutes: 20000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: jest
        run: npm install -g jest
      - name: Start server
        run:  node server.js &
      - name: Wait for server to start
        run: sleep 10 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 20000
        with:
          browser: chrome
      - name: Generate report
        run: npm run coverage
      - name: List directories for debug
        run: ls -R
      - name: Archive coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov-report/
      - name: Slack Notification
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: nodebattleship-pipeline-results
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          #SLACK_ICON: 
          SLACK_MESSAGE: ${{ job.status }}
          SLACK_TITLE: Play through Test Results
          SLACK_USERNAME: NotifyBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

