name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #timeout-minutes: 20000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Start server
        run:  node server.js &
      - name: Wait for server to start
        run: sleep 10 
      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 20000
        with:
          browser: chrome
