name: End-to-end tests
on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge "cypress/results/*.json" > mochawesome.json

      - name: Generate Mochawesome report
        run: npx marge mochawesome.json -f report -o cypress/results

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: cypress/results/report.html
